# -*- coding: utf-8 -*-
"""teste 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTNjJKSDUPeHURzFGgH4mwctp1Oqf_YR
"""

#Washignton Pantoja da silva. 23/08/2024
#disciplina doutorado: fisica computacional
#lista 1, questão 1 a)

# Define o intervalo do somatório
n= 3

# Inicializa a variável que armazenará o resultado
x = 0
#calculando produtorio
prod=1
for j in range(0, n+1):
    if j==0:
        prod=1
    else:
        prod=prod*j
    x+=1/prod
# Exibe o resultado
print("resultado da somatório", x)